---
- name: Disable plugin discovery and auto-download by setting plugin_paths
  hosts: all
  tasks:
    - name: terraform test
      cloud.terraform.terraform:
        project_path: 'project/'
        state: "{{ state }}"
        force_init: true
        plugin_paths:
          - /path/to/plugins_dir_1
          - /path/to/plugins_dir_2
